spring.application.name=adressproject

# MCP Server Konfiguration
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=adressbuch-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.transport=webmvc
spring.ai.mcp.server.sse-message-endpoint=/mcp/message