
spring.application.name=adressproject

# Damit die Anwendung im Browser und in Tests funktioniert
#spring.main.web-application-type=servlet

# MCP-Server Einstellungen
spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.name=adressbuch-mcp-server
spring.ai.mcp.server.version=1.0.0
#spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.type=SYNC
#spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp